config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'restaurants#index'

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  belongs_to :user

  validates :name, length: { minimum: 3 }, uniqueness: true

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  has_many :endorsements

  validates :rating, inclusion: (1..5)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :github]

  has_many :restaurants

  # has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: { new_endorsement_count: @review.endorsements.count }
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    unless current_user.id == @restaurant.user_id
      flash[:notice] = "You need to sign in or sign up before continuing."
      redirect_to '/'
    end
  end

  def update
    restaurant = Restaurant.find(params[:id])
    restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    restaurant = Restaurant.find(params[:id])
    unless current_user.id == restaurant.user_id
      flash[:notice] = "You need to sign in or sign up before continuing."
      redirect_to '/'
    else
      restaurant.destroy
      flash[:notice] = 'Restaurant deleted successfully'

      redirect_to '/restaurants'
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.reviews.create(review_params)

    redirect_to restaurants_path
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth request.env['omniauth.auth']
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def github
    @user = User.from_omniauth request.env['omniauth.auth']
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def star_rating rating
    return rating unless rating.respond_to?(:round)
    remainder = 5 - rating.round
    '★' * rating.round + '☆' * remainder
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YelpCloneForSure
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta(charset="UTF-8")

  %body
    %p.notice= notice
    %p.alert= alert

    - if user_signed_in?
      = link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      = link_to 'Sign in', new_user_session_path
      = link_to 'Sign in with Facebook', user_omniauth_authorize_path(:facebook)
      = link_to 'Sign in with Github', user_omniauth_authorize_path(:github)
      = link_to 'Sign up',
        new_user_registration_path
    = yield

app/views/restaurants/_form.html.haml
= render 'form'

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/restaurants/index.html.haml
%h1 YALP!
- if @restaurants.any?
  - @restaurants.each do |restaurant|

    %h2= link_to restaurant.name, restaurant_path(restaurant)
    %h3 Average rating: #{ star_rating(restaurant.average_rating) }
    = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
    - if user_signed_in? && current_user.id == restaurant.user_id
      = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
      = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete

    %h4
      Review for
      = restaurant.name

    - if restaurant.reviews.any?
      %ul
        - restaurant.reviews.each do |review|
          %li
            #{review.thoughts} Rating: #{star_rating(review.rating)}
            = link_to 'Endorse', review_endorsements_path(review), class: 'endorsements-link'
            %span.endorsements_count= review.endorsements.count
            = 'endorsement'.pluralize review.endorsements.count
    - else
      %p No reviews
- else
  %h1 No restaurants yet!

- if user_signed_in?
  = link_to 'Add a restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, 'Error'
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

= render 'form'

app/views/restaurants/show.html.haml
%h2= @restaurant.name
%section= @restaurant.description

%h3
  Review for
  = @restaurant.name

- if @restaurant.reviews.any?
  %ul
    - @restaurant.reviews.each do |review|
      %li
        = review.thoughts
        = star_rating(review.rating)
- else
  %p No reviews

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'